### ISSUE TITLE
Docker compose configuration

### ISSUE THREAD

**Issue by stefanvanherwijnen** [RealOrangeOne/traefik-pages#5]
I mixed up the alias settings of Docker :disappointed: .
Correct docker.compose.yml:
```yaml
version: "3.3"

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    command: "--log.level=DEBUG"
    ports:
      - "443:443"
      - "8080:8080"
    networks:
      web:
      traefikpages:
        aliases:
          - traefik
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik:/etc/traefik

  traefik-pages:
    container_name: traefik-pages
    image: theorangeone/traefik-pages:latest
    volumes:
      - ./sites:/mnt/sites:ro
    environment:
      - SITES_ROOT=/mnt/sites
      - TRAEFIK_SERVICE=traefik-pages@docker
      - AUTH_PASSWORD=hunter2
#      - TRAEFIK_CERT_RESOLVER=le
    labels:
      - traefik.enable=true
    networks:
      traefikpages:
        aliases:
         - traefikpages

networks:
  web:
    external: true
  traefikpages:
```
<details>
<summary>
OP
</summary>
I'm struggling to get traefik-pages to work. Right now I'm stuck on:
```
traefik        | time="2022-05-03T15:51:26Z" level=error msg="Provider connection error cannot fetch configuration data: Get \"http://hunter2@traefikpages:5000/.traefik-pages/provider\": dial tcp 172.22.0.3:5000: connect: connection refused, retrying in 342.491979ms" providerName=http
```

Any chance you could point me in the right direction?

docker-compose.yml
```yaml
version: "3.3"

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - "443:443"
      - "8080:8080"
    networks:
      web:
      traefikpages:
        aliases:
          - traefikpages
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik:/etc/traefik

  traefik-pages:
    container_name: traefik-pages
    image: theorangeone/traefik-pages:latest
    volumes:
      - ./sites:/mnt/sites:ro
    environment:
      - SITES_ROOT=/mnt/sites
      - TRAEFIK_SERVICE=traefik-pages@docker
      - AUTH_PASSWORD=hunter2
    labels:
      - traefik.enable=true
    ports:
      - "5000:5000"
    networks:
      traefikpages:

networks:
  web:
    external: true
  traefikpages:
```

traefik/traefik.yml
```yaml
entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

ping: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
  http:
    endpoint:
      - "http://hunter2@traefikpages:5000/.traefik-pages/provider"
  file:
    filename: /etc/traefik/file-provider.yml

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
```

traefik/file-provider.yml
```yaml
http:
  services:
    traefik-pages:
      loadBalancer:
        servers:
          - url: "http://traefikpages:5000"
```

I'm guessing it's some trivial error, but I'm failing to find it :upside_down_face: .
</details>
